### PR TITLE
Moved to debhelper compat level 13.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**

### CODE REVIEW

**Comment by ivaylomitrev** [comment]
I will need to put this merge request on hold for now as it has a chance of meddling with some of our internal handling of this package.

**Comment by petterreinholdtsen** [comment]
[ivaylomitrev]
> I will need to put this merge request on hold for now as it has a
> chance of meddling with some of our internal handling of this package.

OK.  How can it affect the handling?  Perhaps I can assist in avoiding
any problems.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by ivaylomitrev** [comment]
> [ivaylomitrev]
> I will need to put this merge request on hold for now as it has a chance of meddling with some of our internal handling of this package.
> OK. How can it affect the handling? Perhaps I can assist in avoiding any problems.
> […](#)
> -- Happy hacking Petter Reinholdtsen

It's entirely internal so there's little I can share. I appreciate the offer though.

**Comment by ivaylomitrev** [comment]
Applied an additional change (on top of the already suggested one) with [PR#70](https://github.com/documaster/noark-extraction-validator/pull/70). I think this PR can be closed :)

**Pull request closed without merging**
